apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    app: grafana-app
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 3000
    protocol: TCP
    name: http
  selector:
    app: grafana-app
