apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-app
spec:
  type: NodePort
  ports:
  - port: 1234
    nodePort: 1234
    protocol: TCP
    name: ssh
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-app
