apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 5000
    protocol: TCP
    name: http
  selector:
    app: phpmyadmin
