apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  labels:
    app: phpmyadmin-app
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 5000
    protocol: TCP
    name: http
  selector:
    app: phpmyadmin-app
