apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: wordpress-app
spec:
  type: NodePort
  ports:
  - port: 5050
    nodePort: 5050
    protocol: TCP
    name: http
  selector:
    app: wordpress-app
